### ISSUE TITLE
Fix Button Alignment for Stories

### ISSUE THREAD

**Issue by aashutoshrathi** [NJACKWinterOfCode/Insta-Downloader-Extension#4]
Current Look:
![bug](https://user-images.githubusercontent.com/21199234/35194289-28ddc48e-fed7-11e7-843d-d3d1170e75ea.png)

**Comment by arunikayadav42** [comment]
I would like to work on this issue.Please guide me to get started with the same.

**Comment by aashutoshrathi** [comment]
Take it.
Send a PR and we will discuss over that.

**Comment by arunikayadav42** [comment]
what is actually wrong with the buttons...I can't make figure out.

**Comment by arunikayadav42** [comment]
Also there is no feature to re-enable the extension once you accidentally click it off while viewing a story.So that should be included as one of the features.
